name: C++ Builder

on: 
  push:
    branches:
    - master

jobs:
  build-win:
   name: Windows Build
   runs-on: windows-latest
   strategy:
     matrix: 
       conf: [Debug, Release]
   steps:
    - name: Download Repository
      uses: actions/checkout@v2
    - name: Vulkan Header Download
      uses: actions/checkout@master
      with:
        repository: KhronosGroup/Vulkan-Headers
    - name: Setup Environment
      run: setx VULKAN_SDK ./Vulkan-Headers
    - name: Prerequesits Check
      run: ./tools/prerequesits_win.bat -s
    - name: Generate Solution
      run: ./tools/generate_project_win.bat -s
    - name: Build
      run: MSBuild.exe ./build/Elemental_Draw.sln
    
  build-linux:
   name: Linux Build
   runs-on: ubuntu-latest
   strategy:
     matrix: 
       conf: [Debug, Release]
   steps:
    - name: Download Repository
      uses: actions/checkout@v2
    - name: Vulkan Header Download
      uses: actions/checkout@master
      with:
        repository: KhronosGroup/Vulkan-Headers
    - name: Setup Environment
      run: |
        export VULKAN_SDK="./Vulkan-Headers"
        sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
    - name: Prerequesits Check
      run: |
        sudo chmod +x ./tools/prerequesits_linux.sh
        sudo ./tools/prerequesits_linux.sh
    - name: Generate Solution
      run: |
        sudo chmod +x ./tools/generate_project_linux.sh
        sudo ./tools/generate_project_linux.sh
    - name: Build
      run: make ./build
