name: C++ Builder

on: 
  push:
    branches:
    - moltenvk-text

jobs:

  build-win:
   name: Windows Build
   runs-on: windows-latest
   strategy:
     matrix: 
       conf: [Release]
   steps:
    - name: Download Repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup Environment
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Generate Solution
      run: ./tools/generate_project_win.bat -s
    - name: Debug
      if: ${{ failure() }}
      run: |
        cd ./build
        ls -la
        tail -n 1000 vcpkg-manifest-install.log
    - name: Build
      run: MSBuild.exe ./build/elemd.sln /p:Configuration=${{ matrix.conf }}
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: elemd-win-${{ matrix.conf }}
        path: ./build/${{ matrix.conf }}/
    
  build-linux:
   name: Linux Build
   runs-on: ubuntu-latest
   strategy:
     matrix: 
       conf: [Release]
   steps:
    - name: Download Repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup Environment
      run: |
        sudo apt update
        sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
    - name: Generate Solution
      run: ./tools/generate_project_linux.sh
    - name: Debug
      if: ${{ failure() }}
      run: |
        cd ./build
        ls -la
        tail -n 1000 vcpkg-manifest-install.log
    - name: Build
      run: |
        cd ./build
        make config=${{ matrix.conf }}
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: elemd-linux-${{ matrix.conf }}
        path: ./build/libelemd*

  build-mac:
   name: Mac Build
   runs-on: macos-latest
   strategy:
     matrix: 
       conf: [Release]
   steps:
    - name: Download Repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Generate Solution
      run: |
        ./tools/generate_project_mac.sh
    - name: Debug
      if: ${{ failure() }}
      run: |
        cd ./build
        ls -la
        tail -n 1000 vcpkg-manifest-install.log
    - name: Build
      run: |
        cd ./build
        make config=${{ matrix.conf }}
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: elemd-mac-${{ matrix.conf }}
        path: |
          ./build/libelemd*
