name: C++ Builder

on: 
  push:
    branches:
    - master

jobs:
  build-win:
   name: Windows Build
   runs-on: windows-latest
   strategy:
     matrix: 
       conf: [Debug, Release]
   steps:
    - name: Download Repository
      uses: actions/checkout@v2
    - name: Setup Environment
      uses: microsoft/setup-msbuild@v1
    - name: Prerequesits Check
      run: ./tools/prerequesits_win.bat -s
    - name: Generate Solution
      run: ./tools/generate_project_win.bat -s
    - name: Build
      run: MSBuild.exe ./build/Elemental_Draw.sln
    
  build-linux:
   name: Linux Build
   runs-on: ubuntu-latest
   strategy:
     matrix: 
       conf: [Debug, Release]
   steps:
    - name: Download Repository
      uses: actions/checkout@v2
    - name: Prerequesits Check
      run: ./tools/prerequesits_linux.sh
    - name: Generate Solution
      run: ./tools/generate_project_linux.sh
    - name: Build
      run: make ./build
